#!/usr/bin/env sh

version() {
	echo "rssgen v0.0.3"
}

usage() {
	cat << EOF
rssgen v0.0.2
Usage: rssgen [options] [path]
rssgen creates a RSS feed file for your project.
Available options are:
  -a 		set the domain
  -c 		set copyright owner
  -d 		set the description
  -t 		set title field
  -s 		use a stylesheet
  -l 		set language field
  -h		show this help
  -v		print the version
With no path given the default is ..
Examples:
  rssgen static/
MIT License
Copyright (c) 2022 Brian Mayer
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
EOF
}

[ "$(uname)" == "Linux" ] && ISLINUX=1

[ -z "$DEBUG" ] || echo "[DEBUG] ISLINUX: $ISLINUX"

builddate() {
	# Mon, 06 Sep 2010 00:01:00 +0000
	date +"%a, %d %b %Y %T %z"
}

builditem() {
	# pubdate="$(grep 'revised"}}' $1 | sed -E 's/.*\}\}(.*)\{\{.*/\1/')"
	pubdate="$(grep '<meta name="\?revised"\?' $1 | sed -E 's/.*"(.*)">/\1/')"
	title="$(grep -m 1 '<title>' $1 | sed -E 's@.*<title>(.*)</title>@\1@')"
	desc="$(grep -m 1 '<meta name="\?description"\?' $1 | sed -E 's/.*"(.*)">/\1/')"
	[ -z "$pubdate" ] && [ $ISLINUX ] && pubdate="$(date -d '@'`stat -c '%Y' $1` +"%a, %d %b %Y %T %z")"

	cat << EOF
	<item>
		<title>${title:-$(basename $1)}</title>
		<description>$desc</description>
		<link>https://$DOMAIN/$1</link>
		<guid>https://$DOMAIN/$1</guid>
		<pubDate>$pubdate</pubDate>
	</item>
EOF
}

# Command line options
while getopts a:c:t:s:l:d:hv name
do
	case $name in
	a) DOMAIN="${OPTARG}" ;;
	c) COPY="${OPTARG}" ;;
	d) DESC="${OPTARG}" ;;
	t) TITLE="${OPTARG}" ;;
	s) STYLE="${OPTARG}" ;;
	l) lang="${OPTARG}" ;;
	h) usage && exit 0 ;;
	v) version && exit 0 ;;
	esac
done

[ -z "$DEBUG" ] || echo "[DEBUG] OPTIND: $OPTIND"

shift $((OPTIND-1))
path="$@"
[ -z "$DEBUG" ] || echo "[DEBUG] path: $path"

[ -z "$lang" ] && lang="en-us"
[ -z "$DOMAIN" ] && DOMAIN="example.com"
[ -z "$COPY" ] && COPY="$DOMAIN"
[ -z "$DESC" ] && DESC="RSS feed for $DOMAIN"

echo '<?xml version="1.0" encoding="UTF-8" ?>'
[ -z "$STYLE" ] || echo "<?xml-stylesheet href=\"$STYLE\" type=\"text/xsl\" media=\"screen\" ?>"
cat << EOF
<rss version="2.0">
<channel>
	<title>$TITLE</title>
	<description>$DESC</description>
	<link>https://$DOMAIN</link>
	<language>$lang</language>
	<copyright>$(date +%Y) $COPY All rights reserved</copyright>
	<lastBuildDate>$(builddate)</lastBuildDate>
	<pubDate>$(builddate)</pubDate>
	<ttl>1800</ttl>
EOF

for f in $(find $path -type f -print)
do
	builditem "${f#./}"
done

cat << EOF
</channel>
</rss>
EOF

